### ISSUE TITLE
`ImportError`: cannot import name 'lossrider' from 'lossrider'

### ISSUE THREAD

**Issue by Haleshot** [jndean/LossRider#2]
from lossrider import lossrider
ImportError: cannot import name 'lossrider' from 'lossrider'

Code to reproduce in marimo (can be run with `marimo edit <filename.py>`:
<details>

```python
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "pandas==2.2.3",
#     "lossrider==0.0.3",
#     "marimo",
# ]
# ///

import marimo

__generated_with = "0.9.14"
app = marimo.App(width="medium")


@app.cell
def __(lossrider, pd):
    # Load a csv that contains columns named "Validation Loss", "Run Count" and "model_type"
    data = pd.read_csv("./sweep_df.csv")

    # Plot it!
    lossrider.lossrider(
        data,
        x="Run Count", 
        y="Validation Loss",
        hue="model_type",
        xlim=(0.6, 340),
        ylim=(3.2, 3.8),
        xticks=(1, 10, 100), 
        yticks=[x/10 for x in range(32, 39)],
        width=1000, height=500, fontsize=30,
        logx=True, grid=False,
        legend=True, legend_loc=(.65, 1),
        outfile='maps/sweep_strategies',
    )
    return (data,)


@app.cell
def __():
    # import libraries
    import marimo as mo
    import pandas as pd
    import micropip
    from lossrider import lossrider
    return lossrider, micropip, mo, pd


if __name__ == "__main__":
    app.run()
```
</details>

The sample code provided in the README in [Usage](https://github.com/jndean/LossRider?tab=readme-ov-file#usage) also doesn't work.

**Comment by Haleshot** [comment]
I cloned the repo and then I noticed the examples could be run on cd'ing to the `examples` folder. The `src/lossrider/__init__.py` seems to import lossrider from .lossridersrc.

**Comment by jndean** [comment]
Hi, thanks for raising an issue.

Your above code works fine for me, though you need to replace `lossrider.lossrider(...)` with just `lossrider(...)`.
 
Your issue is probably due to something in your local environment, e.g. I expect you have probably named your marimo script `lossrider.py`, which means you're trying to import the LossRider function from your own script. Try changing the name of your script to something else and see if that helps.

**Comment by Haleshot** [comment]
> Your above code works fine for me, though you need to replace `lossrider.lossrider(...)` with just `lossrider(...)`.

Not sure how I did not notice this before; thanks!
